### PR TITLE
fix: flakey snippets tests + Dlp samples format's

### PR DESCRIPTION
**Pull request by athakor**
This PR contains : 

1. Override default TotalTimeOut of `DlpServiceClient`, Set `PT10M(600 seconds)` instead `PT5M(300 seconds)` to prevent flaky failures.

2. Run the code formatter `mvn com.coveo:fmt-maven-plugin:format` to fix the `DLP `samples format's

### CODE REVIEW

**Review by pmakani — COMMENTED** [review]
Sample lint is failing and also run formatter inside samples directory

**Review by dmitry-fa — COMMENTED** [review]
It's very difficult to review such big change. I recommend you to submit 2 public PRs, the first just for format, and the second for the fix itself.

**Comment by athakor** [comment]
> It's very difficult to review such big change. I recommend you to submit 2 public PRs, the first just for format, and the second for the fix itself.

@dmitry-fa  we could do that as well, but as we know we run the code formatter before submitting any PR. The problem with separate PR is that if we did in separate PR and run the formatter before submitting the PR then it will affect all the unformatted files so i think it's better to go with single PR.

**Comment by dmitry-fa** [comment]
@athakor 
>  if we did in separate PR and run the formatter before submitting the PR then it will affect all the unformatted files

I can't say I understand what's wrong with the formatting of all files... You can do it withing a single PR but I afraid reviewers will ask you to separate.

**Comment by athakor** [comment]
@dmitry-fa

> I can't say I understand what's wrong with the formatting of all files

even i can't understand why it's affected all files :)

>  I afraid reviewers will ask you to separate.

let's see, will leave on them

**Comment by athakor** [comment]
> Sample lint is failing and also run formatter inside samples directory

@pmakani done PTAL

**Review by pmakani — APPROVED** [review]

**Pull request closed without merging**
